// lib/fakeReviews/pools.ts
// Pool di nomi e commenti per la generazione di recensioni dall'admin.
// Usato sia client-side (anteprima) che server-side (validazione).

export const MALE_FIRST_NAMES = [
  'Marco', 'Giuseppe', 'Antonio', 'Francesco', 'Luigi', 'Salvatore', 'Vincenzo', 'Pietro',
  'Andrea', 'Paolo', 'Stefano', 'Roberto', 'Alessandro', 'Davide', 'Matteo', 'Simone',
  'Fabio', 'Enrico', 'Claudio', 'Gianni',
];

export const FEMALE_FIRST_NAMES = [
  'Maria', 'Anna', 'Giulia', 'Francesca', 'Laura', 'Elena', 'Chiara', 'Sara',
  'Valentina', 'Alessia', 'Federica', 'Silvia', 'Martina', 'Roberta', 'Paola', 'Teresa',
  'Rosa', 'Carmela', 'Lucia', 'Elisa', 'Serena', 'Ilaria', 'Monica', 'Barbara',
  'Cristina', 'Daniela', 'Giovanna', 'Marta', 'Beatrice', 'Camilla',
];

export const SURNAMES = [
  'Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci',
  'Marino', 'Greco', 'Bruno', 'Gallo', 'Conti', 'De Luca', 'Costa', 'Giordano',
  'Mancini', 'Rizzo', 'Lombardi', 'Moretti', 'Barbieri', 'Fontana', 'Santoro', 'Mariani',
  'Rinaldi', 'Caruso', 'Ferrara', 'Galli', 'Martini', 'Leone',
];

export const EMAIL_DOMAINS = ['gmail.com', 'libero.it', 'yahoo.it', 'hotmail.it', 'outlook.it', 'tiscali.it'];

/**
 * Tipo di pool commenti: 'food' per gli oli alimentari (EVO),
 * 'beauty' per i prodotti cosmetici (olio di mandorle, ecc.)
 */
export type CommentPoolType = 'food' | 'beauty';

/**
 * Commenti per fascia di stelle (prodotti alimentari). Il placeholder {prodotto}
 * viene sostituito con il nome del prodotto (in alcuni template).
 */
export const FOOD_COMMENT_POOLS: Record<number, string[]> = {
  5: [
    'Olio eccezionale, si sente subito che è genuino. Lo ricomprerò sicuramente.',
    'Ottimo!',
    'Sapore intenso e fruttato, come l\'olio che faceva mio nonno. Consigliatissimo.',
    'Qualità davvero superiore, niente a che vedere con quello del supermercato.',
    'Spedizione veloce e olio buonissimo. Che dire, perfetto.',
    'Il migliore olio che abbia mai comprato online. Profumo incredibile appena aperto.',
    'Prodotto genuino e di grande qualità. Si sente la differenza sul pane e sulle insalate.',
    'Davvero ottimo, dal colore al profumo al sapore. Complimenti!',
    'Ho provato {prodotto} dopo il consiglio di un amico e non lo cambio più.',
    'Eccellente rapporto qualità prezzo. Arrivato in tempi rapidi e imballato benissimo.',
    'Un olio come si deve, dal gusto deciso. A crudo è spettacolare.',
    'Finalmente un olio vero! Piccante al punto giusto, come deve essere un buon EVO.',
    'Acquisto più che soddisfacente, tutta la famiglia l\'ha apprezzato.',
    'Profumo e sapore da olio appena franto. Top.',
    'Consigliato da amici, si è rivelato all\'altezza delle aspettative. Riordinerò.',
    'Buonissimo, genuino e si sente che è fatto con passione. Grazie!',
    'Perfetto per la bruschetta, sapore autentico del sud.',
    'Qualità impeccabile e servizio clienti gentilissimo. Cinque stelle meritate.',
    'Secondo ordine, conferma piena. {prodotto} è ormai un must in casa nostra.',
    'L\'ho regalato ai miei suoceri e ora lo vogliono comprare anche loro. Ottimo prodotto.',
    'Sapore rotondo e fruttato, retrogusto piccantino. Davvero un bel prodotto.',
    'Non torno più all\'olio industriale. Complimenti per la qualità.',
    'Arrivato prima del previsto, confezione curata e olio fantastico.',
    'Semplicemente il migliore. Da provare assolutamente.',
    'Gusto autentico, si capisce che le olive sono raccolte e lavorate come si deve.',
    'Un profumo che riempie la cucina appena apri la bottiglia. Meraviglioso.',
    'Comprato per curiosità, ora non posso più farne a meno. Qualità vera.',
    'Le lattine sono arrivate perfettamente imballate. Olio dal sapore pieno e deciso.',
    'Da siciliano trapiantato al nord, questo olio mi ha riportato a casa. Grazie di cuore.',
    'Ho fatto assaggiare l\'olio a cena agli amici: tutti a chiedermi dove l\'ho comprato.',
    'Sulla pasta al pomodoro fa la differenza. Un altro livello rispetto al supermercato.',
    'Terzo anno che ordino, qualità sempre costante. Una garanzia.',
    'Olio dal fruttato intenso, leggermente piccante. Esattamente come lo cercavo.',
    'Prodotto eccellente e servizio impeccabile. Mi hanno anche risposto subito su WhatsApp.',
    'Il colore, il profumo, il sapore: tutto perfetto. Complimenti davvero.',
    'Ne ho regalata una bottiglia a Natale, ora me la chiedono tutti. Ottimo!',
    'Si sente che è spremuto a freddo, mantiene tutto il profumo delle olive.',
    'Con la ribollita e le zuppe è la morte sua. Olio strepitoso.',
    'Migliore acquisto dell\'anno. Genuino come quello del frantoio sotto casa dei miei.',
    'Un olio che sa di olive vere, non quelle miscele anonime. Consigliatissimo.',
    'Perfetto equilibrio tra amaro e piccante. Da intenditori.',
    'Mia moglie non vuole più altro olio in casa. Direi che dice tutto.',
    'Arrivato velocissimo, olio buonissimo e prezzo onesto per la qualità. 10 e lode.',
    'Ho provato tanti oli pugliesi e siciliani, questo è tra i migliori in assoluto.',
    'Ottimo anche per friggere il pesce, ma a crudo dà il meglio di sé.',
    'Davvero soddisfatto, si vede la cura in ogni dettaglio, dall\'etichetta all\'imballo.',
    'L\'olio nuovo appena franto è un\'esperienza. Prenotatelo appena esce!',
    'Qualità costante ordine dopo ordine. Ormai siamo clienti fissi.',
    'Sapore ricco e avvolgente, il pane e olio è tornato protagonista a casa nostra.',
    'Finalmente un e-commerce serio: olio top e consegna puntuale.',
    'Le mie bruschette non sono mai state così buone. Grande prodotto.',
    'Un olio onesto e genuino, fatto da gente che ci mette la faccia. Ottimo.',
    'Comprato dopo aver visto la recensione di un blog di cucina: confermo tutto.',
    'Il piccantino sul finale è la firma di un grande olio. Promosso a pieni voti.',
    'Eccezionale sulla carne alla griglia. Non lo cambio con niente.',
    'Bottiglia elegante, perfetta anche da regalare. E il contenuto è ancora meglio.',
    'Cinque stelle meritate: qualità, prezzo e velocità di consegna.',
    'Dopo il primo assaggio ho subito ordinato la scorta per tutto l\'anno.',
  ],
  4: [
    'Molto buono, spedizione un po\' lenta ma ne vale la pena.',
    'Ottimo olio, avrei preferito una confezione un po\' più curata ma la sostanza c\'è tutta.',
    'Buon prodotto, sapore genuino. Il prezzo è leggermente alto ma la qualità si paga.',
    'Olio molto buono, per i miei gusti un filo troppo delicato ma la qualità è evidente.',
    'Soddisfatto dell\'acquisto, buon sapore e consegna nei tempi.',
    'Qualità buona, lo ricomprerei. Quattro stelle solo perché la consegna ha tardato un giorno.',
    'Buon olio genuino, magari un po\' più di piccante non guasterebbe.',
    'Prodotto valido, si sente la genuinità. Consigliato.',
    'Molto valido {prodotto}, buon equilibrio tra fruttato e piccante.',
    'Buono, niente da dire sul prodotto. Migliorabile solo l\'imballaggio.',
    'Ottimo sapore, prezzo nella media. Complessivamente soddisfatto.',
    'Buon acquisto, olio dal gusto pieno. Lo consiglio a chi cerca un EVO autentico.',
    'Qualità decisamente sopra la media. Un piccolo sconto sulle quantità sarebbe gradito.',
    'Arrivato tutto bene, olio buono e genuino come descritto.',
    'Molto soddisfatto, unica nota il tappo un po\' scomodo da dosare.',
    'Sapore autentico, si abbina benissimo a tutto. Promosso.',
    'Buon olio, secondo me perfetto per cucinare. A crudo preferisco un fruttato più intenso.',
    'Consegna regolare e prodotto di qualità. Tornerò a ordinare.',
    'Valido prodotto artigianale, si sente la differenza rispetto alla grande distribuzione.',
    'Buono davvero, quattro stelle piene.',
    'Olio di qualità, il gusto mi convince. Solo il sito potrebbe essere più chiaro sui formati.',
    'Molto buono a crudo, sul soffritto forse è sprecato. Comunque promosso.',
    'Buon fruttato, piccante presente ma non invadente. Lo riprenderò.',
    'Soddisfatto: buon olio e imballaggio curato. Un pelo caro ma ci sta.',
    'Regalo apprezzatissimo, il destinatario mi ha chiesto il sito. Quattro stelle.',
    'Prodotto genuino, si sente la mano artigianale. Consegna nella media.',
    'Buono, intenso al punto giusto. Avrei gradito una scheda di degustazione nel pacco.',
    'Qualità superiore alla media degli oli online che ho provato finora.',
    'Ottimo sul pesce e sulle verdure grigliate. Manca solo il formato più grande.',
    'Convinto dall\'acquisto, sapore pulito e autentico. Riordinerò a breve.',
    'Buon olio del sud, corposo come piace a me. La bottiglia scura protegge bene.',
    'Arrivato integro e ben protetto. Il sapore non delude, quattro stelle.',
    'Per il prezzo che ha, la qualità è ottima. Non arrivo a cinque solo per il tappo.',
    'Gusto deciso che ricorda l\'olio dei contadini di una volta. Bene così.',
    'Servizio clienti disponibile e olio valido. Esperienza positiva nel complesso.',
    'Piacevolmente sorpreso, temevo il solito olio da marketing e invece è roba seria.',
    'Buono su tutto, dalla caprese ai legumi. Lo consiglio agli amici.',
    'Secondo acquisto, qualità confermata. Il piccante quest\'anno è un filo più leggero.',
    'Prodotto onesto e genuino, spedizione regolare. Soddisfatto.',
    'Un buon extravergine, profumato e corposo. Ci siamo quasi per le cinque stelle.',
  ],
  3: [
    'Buon prodotto, prezzo un po\' alto rispetto ad altri oli simili.',
    'Olio discreto, mi aspettavo un sapore più intenso.',
    'Nella norma, non mi ha entusiasmato ma è comunque un olio genuino.',
    'Prodotto onesto. La spedizione però ha tardato qualche giorno.',
    'Buono ma non eccezionale, forse le mie aspettative erano troppo alte.',
    'Sapore gradevole ma per il prezzo mi aspettavo qualcosa in più.',
    'Discreto, lo userò per cucinare. A crudo preferisco altro.',
    'Olio nella media, confezione arrivata con un po\' di ritardo.',
    'Non male, ma ho assaggiato di meglio nella stessa fascia di prezzo.',
    'Prodotto corretto, qualità onesta. Tre stelle.',
    'Mi aspettavo un fruttato più deciso da {prodotto}, comunque un prodotto dignitoso.',
    'Sufficiente. Il servizio è stato buono, il sapore per me è troppo delicato.',
    'Olio corretto ma nulla che giustifichi il prezzo rispetto al mio solito frantoio.',
    'Tre stelle: buono a crudo, un po\' amaro per i miei gusti in cottura.',
    'Il primo ordine era arrivato meglio imballato, questa volta la scatola era ammaccata.',
    'Prodotto nella media, il profumo promette più di quello che il sapore mantiene.',
    'Né buono né cattivo, un olio come tanti. Forse mi aspettavo troppo.',
    'Qualità discreta ma il formato piccolo finisce subito, servirebbe una tanica.',
    'Onestamente non ho sentito tutta questa differenza rispetto a oli più economici.',
    'Va bene per cucinare, per il pinzimonio continuo a preferire il mio solito.',
    'Consegna puntuale ma l\'olio non mi ha lasciato il segno. Sufficiente.',
    'Discreto rapporto qualità prezzo, ma non credo che riordinerò.',
  ],
  2: [
    'Olio arrivato con la confezione danneggiata, il prodotto in sé è discreto.',
    'Non mi ha convinto, sapore troppo leggero per i miei gusti.',
    'Consegna lenta e prezzo alto. L\'olio è nella media.',
    'Mi aspettavo molto di più dalle recensioni. Deluso.',
    'Qualità non all\'altezza del prezzo secondo me.',
    'Sapore anonimo, non lo ricomprerei.',
    'Il prodotto è arrivato in ritardo e la bottiglia era sporca d\'olio all\'esterno.',
    'Sotto le aspettative, peccato.',
    'Due stelle: il corriere ha lasciato il pacco sotto la pioggia e nessuno mi ha avvisato.',
    'L\'olio sa di poco, per il prezzo pagato mi aspettavo tutt\'altra intensità.',
    'La bottiglia perdeva leggermente dal tappo, metà etichetta era unta.',
    'Deludente, il mio fruttivendolo vende di meglio a meno.',
    'Ho fatto un ordine grande fidandomi delle recensioni, non lo rifarei.',
    'Il sapore non è male ma la gestione della spedizione è stata un disastro.',
  ],
  1: [
    'Prodotto non conforme alle mie aspettative, esperienza deludente.',
    'Consegna in forte ritardo e nessuna risposta alle mie email. Non ci siamo.',
    'Non mi è piaciuto per niente, sapore che non sa di nulla.',
    'Bottiglia arrivata rotta. Poi risolto con il reso ma che disagio.',
    'Deluso dall\'acquisto, non lo consiglio.',
    'Per me bocciato, ho pagato tanto per un olio qualunque.',
    'Pacco arrivato dopo due settimane e con una bottiglia in meno. Esperienza pessima.',
    'Olio dal gusto piatto, niente a che vedere con le foto e le descrizioni del sito.',
    'Una stella per la spedizione infinita. Il prodotto non l\'ho nemmeno finito.',
    'Mi è arrivato un formato diverso da quello ordinato. Che confusione.',
    'Non ci siamo proprio: prezzo alto, olio mediocre. Non riordino.',
  ],
};

/**
 * Commenti per fascia di stelle (prodotti beauty/cosmetici, es. olio di mandorle).
 */
export const BEAUTY_COMMENT_POOLS: Record<number, string[]> = {
  5: [
    'Olio meraviglioso, la pelle resta morbida e idratata tutto il giorno. Lo adoro!',
    'Fantastico!',
    'Si assorbe subito senza ungere, e il profumo è delicatissimo. Consigliato.',
    'Lo uso tutte le sere dopo la doccia, pelle di seta. Non lo cambio più.',
    'Prodotto naturale e genuino, si sente la differenza rispetto a quelli industriali.',
    'Perfetto per i massaggi, texture leggera e profumo piacevole.',
    'Lo uso anche sui capelli come impacco, risultato incredibile. Super consigliato.',
    'Qualità eccellente, {prodotto} è ormai fisso nella mia routine.',
    'Ottimo sulla pelle sensibile, nessuna irritazione. Finalmente un prodotto pulito.',
    'Idratazione perfetta senza effetto unto. Arrivato anche in tempi rapidissimi.',
    'L\'ho comprato per le smagliature in gravidanza su consiglio dell\'ostetrica. Ottimo.',
    'Profumo naturale e delicato, niente a che vedere con i profumi artificiali. Top.',
    'Regalo azzeccatissimo, mia sorella lo usa ogni giorno e me lo ha chiesto di nuovo.',
    'Prodotto puro e di qualità, si vede che è artigianale. Cinque stelle.',
    'La mia pelle secca è rinata. Riacquisterò sicuramente.',
    'Perfetto anche per la pelle delicata dei bambini. Promosso a pieni voti.',
    'Davvero un ottimo olio, nutriente e leggero. Il flacone dura tantissimo.',
    'Lo metto sulle punte dei capelli prima della piega: addio doppie punte.',
    'Dopo anni di creme costose ho scoperto che mi bastava questo. Fantastico.',
    'Struccante naturale perfetto, delicato anche sugli occhi. Non torno indietro.',
    'Pelle nutrita e luminosa senza siliconi e profumi sintetici. Che scoperta!',
    'Lo uso sulle cuticole e sulle mani screpolate dal lavoro: risultato top.',
    'Consigliato dalla mia estetista, ora lo compro solo qui. Qualità superiore.',
    'Ottimo dopo la depilazione, calma subito la pelle. Lo consiglio a tutte.',
    'Ne bastano poche gocce, il flacone dura mesi. Qualità che si vede e si sente.',
    'Perfetto per il massaggio del bebè, delicatissimo. La pediatra ha approvato.',
    'Mi ha risolto le pellicine e le mani secche dell\'inverno. Non lo lascio più.',
    'Ideale dopo il sole, la pelle beve letteralmente questo olio. Estate salvata.',
    'Il mio parrucchiere mi ha chiesto cosa uso sui capelli. Direi che basta questo.',
    'Puro, senza aggiunte strane in etichetta. Finalmente un prodotto trasparente.',
    'Compro {prodotto} ormai da un anno, pelle visibilmente più elastica.',
    'Arrivato con un packaging curatissimo, perfetto anche come idea regalo.',
    'Uso quotidiano su viso e collo: texture setosa e zero brufoli. Promosso!',
    'Mia figlia adolescente lo usa per la pelle secca, entusiaste entrambe.',
    'Meglio di tanti oli blasonati che costano il triplo. Acquisto furbissimo.',
    'Massaggio serale sulle gambe e via la pesantezza. Il mio momento relax.',
    'Profuma di buono, di pulito, non di profumeria chimica. Lo adoro.',
    'Cinque stelle piene: qualità, prezzo giusto e spedizione veloce.',
  ],
  4: [
    'Molto buono, idrata bene. Avrei preferito un dosatore più pratico.',
    'Ottimo prodotto, si assorbe bene. Quattro stelle solo per la consegna un po\' lenta.',
    'Buon olio naturale, il profumo è molto tenue, a me piacerebbe più deciso.',
    'Valido per pelle e capelli, prezzo leggermente alto ma la qualità c\'è.',
    'Soddisfatta dell\'acquisto, pelle morbida già dopo pochi utilizzi.',
    'Buona qualità, texture un filo ricca per l\'estate ma d\'inverno è perfetto.',
    'Lo uso per i massaggi, scorre bene e nutre. Consigliato.',
    'Prodotto valido e naturale, {prodotto} mi ha convinto. Ricomprerò.',
    'Buono, si assorbe abbastanza in fretta. Confezione curata.',
    'Idrata molto bene, unica pecca il tappo che perde qualche goccia.',
    'Contenta dell\'acquisto, prodotto genuino e spedizione nei tempi.',
    'Buon rapporto qualità prezzo per un olio puro. Promosso.',
    'Molto valido sui capelli, sul viso per me è un po\' troppo ricco.',
    'Buon prodotto naturale, il flacone in vetro è bello ma scivola con le mani unte.',
    'Idrata a lungo, quattro stelle perché vorrei anche il formato grande.',
    'Piacevole da usare, assorbimento nella media. Nel complesso soddisfatta.',
    'Regalato a mia madre che ha la pelle secca: contenta lei, contenta io.',
    'Fa quello che promette, senza miracoli ma con costanza. Riordinerò.',
    'Buono per il massaggio sportivo, scorre bene e non appiccica troppo.',
    'Qualità evidente, il profumo però svanisce in fretta. Quattro stelle.',
    'Ottimo sulle smagliature in prevenzione, lo uso da due mesi. Fin qui bene.',
    'Prodotto onesto e delicato, nessuna reazione sulla mia pelle reattiva.',
    'Buon olio, arrivato ben protetto. Il contagocce potrebbe essere migliore.',
    'Soddisfatta: pelle più morbida già dopo una settimana di utilizzo.',
    'Valido alleato per l\'inverno, d\'estate preferisco qualcosa di più leggero.',
    'Mi trovo bene, unico neo il prezzo un po\' sopra la media. Ma la qualità c\'è.',
  ],
  3: [
    'Prodotto discreto, idrata ma non mi ha stupito.',
    'Nella media, mi aspettavo un profumo più gradevole.',
    'Buono ma un po\' caro rispetto ad altri oli di mandorle.',
    'Texture per me troppo grassa, impiega un po\' ad assorbirsi.',
    'Onesto, fa il suo dovere. Niente di più, niente di meno.',
    'Il prodotto è buono ma la spedizione ha tardato qualche giorno.',
    'Discreto, lo uso per i massaggi ma sulla pelle del viso preferisco altro.',
    'Sufficiente, forse le mie aspettative erano troppo alte.',
    'Idrata, sì, ma non più della crema che uso di solito e che costa meno.',
    'Tre stelle: prodotto valido ma la consegna è arrivata oltre i tempi indicati.',
    'Sulla mia pelle grassa non è l\'ideale, meglio per chi ha pelle secca.',
    'Il contagocce eroga troppo prodotto, se ne spreca parecchio.',
    'Nella media dei prodotti naturali, niente che mi abbia fatto gridare al miracolo.',
    'Carino il packaging, il contenuto però non mi ha conquistato del tutto.',
    'Utile per i massaggi, per il viso lo trovo troppo pesante.',
    'Prodotto dignitoso ma il rapporto qualità prezzo non mi convince fino in fondo.',
  ],
  2: [
    'Flacone arrivato con un po\' di prodotto fuoriuscito, peccato.',
    'Non mi ha convinto, l\'ho trovato troppo unto.',
    'Mi aspettavo di più dalle recensioni, per ora deluso.',
    'Il profumo non mi piace e il prezzo è alto per quello che offre.',
    'Consegna lenta e prodotto nella media. Non ricomprerò.',
    'Sulla mia pelle non ha fatto la differenza promessa. Due stelle.',
    'Lascia una patina unta che non si assorbe, devo tamponare con l\'asciugamano.',
    'Flacone più piccolo di come sembrava dalle foto. Rimasta delusa.',
    'Il tappo si è rotto al secondo utilizzo, prodotto sprecato nel cassetto.',
    'Non fa miracoli e il profumo non mi convince. Non lo riprenderò.',
    'Ordine arrivato in ritardo e senza il campioncino promesso. Peccato.',
  ],
  1: [
    'Esperienza deludente, prodotto non all\'altezza delle aspettative.',
    'Flacone arrivato danneggiato e assistenza lenta a rispondere.',
    'Non mi è piaciuto per niente, non fa quello che promette.',
    'Bocciato, ho pagato tanto per un olio qualunque.',
    'Mi ha irritato la pelle, ho dovuto smettere dopo due giorni. Sconsigliato.',
    'Pacco mai arrivato la prima volta, rispedito dopo mille solleciti. Mai più.',
    'Completamente diverso da come descritto sul sito. Delusione totale.',
    'Unto, pesante e con un odore che non sopporto. Soldi buttati.',
    'Una stella solo perché zero non si può mettere. Assistenza inesistente.',
  ],
};

export const COMMENT_POOLS_BY_TYPE: Record<CommentPoolType, Record<number, string[]>> = {
  food: FOOD_COMMENT_POOLS,
  beauty: BEAUTY_COMMENT_POOLS,
};
